### ISSUE TITLE
Not connectable 

### ISSUE THREAD

**Issue by Rowdy** [JohnKearney1/Solana-API#1]
Hello mate,
unfortunately I can not connect to any endooints. Is your website up and running?
Thanks in advance

**Comment by JohnKearney1** [comment]
Hey there! 
I'm currently in the process of relocating the machines that host the server, I'll be able to have it running again by the end of the day, will update the docs / this thread when It's back online.

**Comment by Rowdy** [comment]
Awesome. Thanks

**Comment by JohnKearney1** [comment]
Sorry for the delay-

The server is up and running again: Took some time for the nameserver / DNS changes to propagate. 

Accessible via http://api.kearneyjohn.com:8042/... Docs are [here](https://docs.kearneyjohn.com/docs/Solana%20REST%20API/Endpoints).
